# docker compose version
version: '1.0.0'

services:
  redis:
    # Redis is in-memory data structure store that can be used as a NoSQL database, cache, and message broker
    # it's known for its speed and flexibility due to storing data in RAM
    image: redis:7
    ports:
      - '6379:6379' #external:internal port
    expose:
      - '6379'
    environment:
      TERM: xterm-256color #Define terminal with color for visual orientation

  db: #DB CONTAINER
    container_name: hb-db
    image: postgres:16 #Use https://hub.docker.com/_/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TERM: xterm-256color #Define terminal with color for visual orientation
    ports:
      - '5432:5432' #default port for postgres
    expose:
      - '5432'

  web: #APP CONTAINER
    container_name: hb-web
    build: .
    stdin_open: true
    tty: true
    entrypoint: config/setup_app.sh
    command: bash -c "rails s -p 3000 -b '0.0.0.0'"
    environment:
      TERM: xterm-256color #Define terminal with color for visual orientation
    env_file:
      - ./app/.env.development #Use file to point for our db container
    volumes:
      - .:/home/app/web
    ports:
      - '3000:3000'

  worker:
    container_name: hb-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      TERM: xterm-256color #Define terminal with color for visual orientation
    env_file:
      - ./app/.env.development #Use file to point for our db container
    volumes:
      - .:/home/app/web