default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: db
  port: 3306

development:
  <<: *default
  database: house_budget_api_development

test:
  <<: *default
  database: house_budget_api_test

production:
  <<: *default
  database: house_budget_api_production
  username: house_budget_api
  password: <%= ENV["HOUSE_BUDGET_API_DATABASE_PASSWORD"] %>
