default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: db
  port: 3306

development:
  <<: *default
  database: house_budget_api_development

test:
  <<: *default
  database: house_budget_api_test
  host: 127.0.0.1
  port: 3307


production:
  primary: &primary_production
    <<: *default
    database: house_budget_api_production
    username: house_budget_api
    password: <%= ENV["HOUSE_BUDGET_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: house_budget_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: house_budget_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: house_budget_api_production_cable
    migrations_paths: db/cable_migrate
